name: End-to-end tests
on:
  pull_request:
    branches:
      - main
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 8
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: pnpm build
          start: pnpm start
          wait-on: 'http://localhost:3000'
        env:
          NEXT_PUBLIC_SUPABASE_URL: https://hutyvvlksbsnsprmruey.supabase.co
          NEXT_PUBLIC_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1dHl2dmxrc2JzbnNwcm1ydWV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTAwNTgyOTYsImV4cCI6MjAyNTYzNDI5Nn0.YK11spmvPqZVaT8ekk3xWUWDG6WHGpWZWPbc3hRqTxM
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
